### ISSUE TITLE
Add Tablayout with Fragments for Movies Category (same like movies details tabs)

### ISSUE THREAD

**Issue by esQmo** [HadySalhab/Movies#1]
How to make this project bit complex by adding a Tablayout + ViewPager that will show movies category and fragments to display each category with a list of corresponding movies.
I'm a bit new to MVVM and Dependency Injection so I don't know where to start

**Comment by esQmo** [comment]
@HadySalhab Please HELP!!!!!

**Comment by HadySalhab** [comment]
Hey,
Check 
1-DetailActivity of this app or 
2-"sources-category" from this https://github.com/HadySalhab/NewsFeed-MVI-Dagger

Main point:
1- create a hosting Activity (or parent Activity) that will host the ViewPager.
2- fire a request from your parent (activity->viewmodel->repo->network Layer) 
3- observe the request from your ViewModel (viewmodel->repo->network Layer) using LiveData
4- observe the data from your children fragments (fragments->viewModel)
5- filter the data based on the categories

**Comment by esQmo** [comment]
Hey, thanks for the reply. I tried doing that following the DetailsActivity but there is no way to get data from the ViewModel and pass it to the TabLayout. My list has always 0 size. I need the tab title and item counts come from the API response. In there, you has tabs size hardcoded to 4 and the titles are manually set.
I'm just trying to fetch categories from my api and have followed your example but no success
